# Generated by Django 5.1.6 on 2026-04-08 11:06

import colleges.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('overview', models.TextField()),
                ('message', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('province', models.CharField(blank=True, choices=[('province_1', 'Province No. 1'), ('province_2', 'Province No. 2'), ('bagmati', 'Bagmati Province'), ('gandaki', 'Gandaki Province'), ('lumbini', 'Lumbini Province'), ('karnali', 'Karnali Province'), ('sudurpashchim', 'Sudurpashchim Province')], max_length=100, null=True)),
                ('map', models.TextField(blank=True, help_text='Embed map URL with width value 950 and height value 500.', null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=colleges.models.logo_upload_to)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to=colleges.models.cover_upload_to)),
                ('affiliation', models.CharField(choices=[('tribhuvan', 'Tribhuvan University'), ('pokhara', 'Pokhara University'), ('kathmandu', 'Kathmandu University'), ('gandaki', 'Gandaki University'), ('purbanchal', 'Purbanchal University'), ('foreign', 'Foreign University')], max_length=50)),
                ('foreign_university_name', models.CharField(blank=True, max_length=255, null=True)),
                ('admission', models.BooleanField(default=False, help_text='Toggle admission period.')),
                ('last_admissions', models.IntegerField(default=0)),
                ('current_admissions', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('not_decided', 'Not Decided')], default='not_decided', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=colleges.models.gallery_upload_to)),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('year', models.CharField(max_length=100)),
                ('field', models.CharField(choices=[('engineering', 'Engineering'), ('cit', 'Computer and Information Technology'), ('management', 'Management'), ('st', 'Science and Technology'), ('medicine', 'Medicine'), ('law', 'Law')], max_length=255)),
                ('level', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master')], max_length=255)),
                ('affiliation', models.CharField(choices=[('tribhuvan', 'Tribhuvan University'), ('pokhara', 'Pokhara University'), ('kathmandu', 'Kathmandu University'), ('gandaki', 'Gandaki University'), ('purbanchal', 'Purbanchal University'), ('foreign', 'Foreign University')], max_length=50)),
                ('foreign_university_name', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField()),
                ('eligibility', models.TextField(blank=True, null=True)),
                ('admission_criteria', models.TextField(blank=True, null=True)),
                ('job_prospect', models.TextField(blank=True, null=True)),
                ('prospect_career', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
