# Generated by Django 5.1.6 on 2026-04-08 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='collegeadminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college_admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='college',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_college', to='colleges.collegeadminprofile'),
        ),
        migrations.AddField(
            model_name='collegecourse',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_courses', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='colleges.collegecourse'),
        ),
        migrations.AddField(
            model_name='collegeimage',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='collegeview',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='collegecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_courses', to='colleges.course'),
        ),
        migrations.AddField(
            model_name='rating',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('user', 'college', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='collegecourse',
            unique_together={('college', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'college')},
        ),
    ]
