# Generated by Django 5.1.4 on 2025-02-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_institution_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='province',
            field=models.CharField(blank=True, choices=[('province_1', 'Province No. 1'), ('province_2', 'Province No. 2'), ('bagmati', 'Bagmati Province'), ('gandaki', 'Gandaki Province'), ('lumbini', 'Lumbini Province'), ('karnali', 'Karnali Province'), ('sudurpashchim', 'Sudurpashchim Province')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
