# Generated by Django 5.1.4 on 2025-03-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_userinteraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInteraction',
        ),
    ]
