# Generated by Django 5.1.4 on 2025-03-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_delete_userinteraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='program',
        ),
    ]
