# Generated by Django 5.1.4 on 2025-04-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_remove_institution_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionadmin',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
