# Generated by Django 6.0.4 on 2026-04-22 04:25

import django.utils.timezone
from django.db import migrations, models


def backfill_email_identities(apps, schema_editor):
    EmailIdentity = apps.get_model('app', 'EmailIdentity')
    SuperAdmin = apps.get_model('app', 'SuperAdmin')
    User = apps.get_model('app', 'User')
    InstitutionAdmin = apps.get_model('app', 'InstitutionAdmin')

    seen_emails = {}
    backfill_rows = []

    account_sets = [
        ('superadmin', SuperAdmin.objects.all()),
        ('user', User.objects.all()),
        ('institutionadmin', InstitutionAdmin.objects.all()),
    ]

    for owner_type, queryset in account_sets:
        for account in queryset.iterator():
            if not account.email:
                continue

            normalized_email = account.email.strip().lower()
            owner_ref = (owner_type, account.pk)

            if normalized_email in seen_emails and seen_emails[normalized_email] != owner_ref:
                existing_ref = seen_emails[normalized_email]
                raise RuntimeError(
                    f"Global email collision detected for '{normalized_email}' between {existing_ref} and {owner_ref}. "
                    "Resolve duplicate emails first, then re-run migration."
                )

            seen_emails[normalized_email] = owner_ref
            backfill_rows.append(
                EmailIdentity(email=normalized_email, owner_type=owner_type, owner_id=account.pk)
            )

    if backfill_rows:
        EmailIdentity.objects.bulk_create(backfill_rows)


def rollback_email_identities(apps, schema_editor):
    EmailIdentity = apps.get_model('app', 'EmailIdentity')
    EmailIdentity.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_institution_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('owner_type', models.CharField(choices=[('superadmin', 'Super Admin'), ('user', 'User'), ('institutionadmin', 'Institution Admin')], max_length=20)),
                ('owner_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['owner_type', 'owner_id'], name='email_identity_owner_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner_type', 'owner_id'), name='uniq_email_identity_owner')],
            },
        ),
        migrations.RunPython(backfill_email_identities, rollback_email_identities),
    ]
