# Generated by Django 6.0.4 on 2026-04-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_emailidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otp',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
