# Generated by Django 6.0.4 on 2026-04-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_otp_failed_attempts_otp_locked_until'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['latitude', 'longitude'], name='inst_lat_lng_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['latitude', 'longitude'], name='user_lat_lng_idx'),
        ),
    ]
