# Generated by Django 6.0.4 on 2026-04-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_institution_inst_lat_lng_idx_user_user_lat_lng_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Admission_Criteria',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Job_Prospect',
        ),
        migrations.AddField(
            model_name='institutionadmin',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='institution_admin/profiles/'),
        ),
    ]
